// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AccessKeyBearerAuthScopes = "accessKeyBearerAuth.Scopes"
	ApiKeyAuthScopes          = "apiKeyAuth.Scopes"
	BearerAuthScopes          = "bearerAuth.Scopes"
	FirebaseCookieAuthScopes  = "firebaseCookieAuth.Scopes"
)

// Defines values for ImportStatus.
const (
	Canceled   ImportStatus = "canceled"
	Failed     ImportStatus = "failed"
	Finished   ImportStatus = "finished"
	Processing ImportStatus = "processing"
	Waiting    ImportStatus = "waiting"
)

// Defines values for ResourceType.
const (
	Categories    ResourceType = "categories"
	Holidays      ResourceType = "holidays"
	Products      ResourceType = "products"
	StoreStatuses ResourceType = "storeStatuses"
	Stores        ResourceType = "stores"
	Userstores    ResourceType = "userstores"
)

// Defines values for GetProductsParamsSort.
const (
	GetProductsParamsSortId   GetProductsParamsSort = "id"
	GetProductsParamsSortName GetProductsParamsSort = "name"
)

// Defines values for GetProductsParamsOrder.
const (
	GetProductsParamsOrderAsc   GetProductsParamsOrder = "asc"
	GetProductsParamsOrderDesc  GetProductsParamsOrder = "desc"
	GetProductsParamsOrderEmpty GetProductsParamsOrder = ""
)

// Defines values for GetStoresParamsSort.
const (
	GetStoresParamsSortId   GetStoresParamsSort = "id"
	GetStoresParamsSortName GetStoresParamsSort = "name"
)

// Defines values for GetStoresParamsOrder.
const (
	GetStoresParamsOrderAsc   GetStoresParamsOrder = "asc"
	GetStoresParamsOrderDesc  GetStoresParamsOrder = "desc"
	GetStoresParamsOrderEmpty GetStoresParamsOrder = ""
)

// Defines values for GetStoresSalesParamsSort.
const (
	Id             GetStoresSalesParamsSort = "id"
	Name           GetStoresSalesParamsSort = "name"
	SalesFloorArea GetStoresSalesParamsSort = "salesFloorArea"
)

// Defines values for GetStoresSalesParamsOrder.
const (
	Asc   GetStoresSalesParamsOrder = "asc"
	Desc  GetStoresSalesParamsOrder = "desc"
	Empty GetStoresSalesParamsOrder = ""
)

// AccessKey defines model for AccessKey.
type AccessKey struct {
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updatedAt"`
	Value     string     `json:"value"`
}

// Category カテゴリーデータ
type Category struct {
	CategoryId1   string `json:"categoryId1"`
	CategoryId2   string `json:"categoryId2"`
	CategoryId3   string `json:"categoryId3"`
	CategoryId4   string `json:"categoryId4"`
	CategoryId5   string `json:"categoryId5"`
	CategoryName1 string `json:"categoryName1"`
	CategoryName2 string `json:"categoryName2"`
	CategoryName3 string `json:"categoryName3"`
	CategoryName4 string `json:"categoryName4"`
	CategoryName5 string `json:"categoryName5"`
}

// CategoryGroup カテゴリーグループデータ
type CategoryGroup struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        string     `json:"id"`
	Level     float32    `json:"level"`
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// CategoryGroupCategory カテゴリーグループカテゴリーデータ
type CategoryGroupCategory struct {
	CategoryGroupId *string `json:"categoryGroupId"`
	CategoryId1     string  `json:"categoryId1"`
	CategoryId2     string  `json:"categoryId2"`
	CategoryId3     string  `json:"categoryId3"`
	CategoryId4     string  `json:"categoryId4"`
	CategoryId5     string  `json:"categoryId5"`
	CategoryName1   string  `json:"categoryName1"`
	CategoryName2   string  `json:"categoryName2"`
	CategoryName3   string  `json:"categoryName3"`
	CategoryName4   string  `json:"categoryName4"`
	CategoryName5   string  `json:"categoryName5"`
}

// CategoryGroupUpdate カテゴリーグループデータ update
type CategoryGroupUpdate struct {
	Level float32 `json:"level"`
	Name  string  `json:"name"`
}

// CategoryTree カテゴリーツリーデータ
type CategoryTree struct {
	Categories []CategoryTree `json:"categories"`
	Id         string         `json:"id"`
	Name       string         `json:"name"`
}

// CreateManagersResponse defines model for CreateManagersResponse.
type CreateManagersResponse struct {
	Managers []ManagerObject `json:"managers"`
}

// DeleteManagersResponse defines model for DeleteManagersResponse.
type DeleteManagersResponse struct {
	Managers []ManagerObject `json:"managers"`
}

// Error defines model for Error.
type Error = map[string]interface{}

// FileUpload defines model for FileUpload.
type FileUpload struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// GetCategoriesAsTreeResponse defines model for GetCategoriesAsTreeResponse.
type GetCategoriesAsTreeResponse struct {
	Categories []CategoryTree `json:"categories"`
	TotalCount int            `json:"totalCount"`
}

// GetCategoriesResponse defines model for GetCategoriesResponse.
type GetCategoriesResponse struct {
	Categories []Category `json:"categories"`
	TotalCount int        `json:"totalCount"`
}

// GetCategoryGroupCategoriesResponse defines model for GetCategoryGroupCategoriesResponse.
type GetCategoryGroupCategoriesResponse struct {
	CategoryGroupCategories []CategoryGroupCategory `json:"categoryGroupCategories"`
	TotalCount              int                     `json:"totalCount"`
}

// GetCategoryGroupResponse defines model for GetCategoryGroupResponse.
type GetCategoryGroupResponse struct {
	// CategoryGroup カテゴリーグループデータ
	CategoryGroup CategoryGroup `json:"categoryGroup"`
}

// GetCategoryGroupsResponse defines model for GetCategoryGroupsResponse.
type GetCategoryGroupsResponse struct {
	CategoryGroups []CategoryGroup `json:"categoryGroups"`
	TotalCount     int             `json:"totalCount"`
}

// GetHolidaysResponse defines model for GetHolidaysResponse.
type GetHolidaysResponse struct {
	Holidays   []Holiday `json:"holidays"`
	TotalCount int       `json:"totalCount"`
}

// GetImportsResponse defines model for GetImportsResponse.
type GetImportsResponse struct {
	Imports    []Import `json:"imports"`
	TotalCount int      `json:"totalCount"`
}

// GetManagersForStoreResponse defines model for GetManagersForStoreResponse.
type GetManagersForStoreResponse struct {
	Managers   []ManagerObject `json:"managers"`
	TotalCount int             `json:"totalCount"`
}

// GetManagersResponse defines model for GetManagersResponse.
type GetManagersResponse struct {
	Stores     []StoreObject `json:"stores"`
	TotalCount int           `json:"totalCount"`
}

// GetProductsResponse defines model for GetProductsResponse.
type GetProductsResponse struct {
	Products   []Product `json:"products"`
	TotalCount int       `json:"totalCount"`
}

// GetStoresResponse defines model for GetStoresResponse.
type GetStoresResponse struct {
	Stores     []Store `json:"stores"`
	TotalCount int     `json:"totalCount"`
}

// GetStoresSalesResponse defines model for GetStoresSalesResponse.
type GetStoresSalesResponse struct {
	Stores     []StoreSales `json:"stores"`
	TotalCount int          `json:"totalCount"`
}

// Holiday 祝日データ
type Holiday struct {
	Date *openapi_types.Date `json:"date,omitempty"`
	Name *string             `json:"name,omitempty"`
}

// Import インポート処理の状態
type Import struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	Output    *string   `json:"output"`

	// Status インポート状況
	Status    ImportStatus `json:"status"`
	UpdatedAt time.Time    `json:"updatedAt"`
}

// ImportStatus インポート状況
type ImportStatus string

// ManagerObject 担当者のオブジェクト
type ManagerObject struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// Product 商品データ
type Product struct {
	CategoryId1 string `json:"categoryId1"`
	CategoryId2 string `json:"categoryId2"`
	CategoryId3 string `json:"categoryId3"`
	CategoryId4 string `json:"categoryId4"`
	CategoryId5 string `json:"categoryId5"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	Note        string `json:"note"`
	Price       *int   `json:"price"`
}

// ResourceType インポート対象
type ResourceType string

// Store 店舗データ
type Store struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// StoreObject 店舗のオブジェクト
type StoreObject struct {
	Id *string `json:"id,omitempty"`

	// LastUpdatedOn 更新日時
	LastUpdatedOn *openapi_types.Date `json:"lastUpdatedOn,omitempty"`
	Managers      *[]ManagerObject    `json:"managers,omitempty"`
	Name          string              `json:"name"`
}

// StoreSales 店舗売り場面積データ
type StoreSales struct {
	Id             *string  `json:"id,omitempty"`
	Name           *string  `json:"name,omitempty"`
	SalesFloorArea *float32 `json:"salesFloorArea,omitempty"`
}

// UpdateCategoryGroupResponse defines model for UpdateCategoryGroupResponse.
type UpdateCategoryGroupResponse struct {
	// CategoryGroup カテゴリーグループデータ
	CategoryGroup CategoryGroup `json:"categoryGroup"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// DeleteCategoryParams defines parameters for DeleteCategory.
type DeleteCategoryParams struct {
	CategoryId1 string `form:"categoryId1" json:"categoryId1"`
	CategoryId2 string `form:"categoryId2" json:"categoryId2"`
	CategoryId3 string `form:"categoryId3" json:"categoryId3"`
	CategoryId4 string `form:"categoryId4" json:"categoryId4"`
	CategoryId5 string `form:"categoryId5" json:"categoryId5"`
}

// GetCategoriesParams defines parameters for GetCategories.
type GetCategoriesParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetCategoriesAsTreeParams defines parameters for GetCategoriesAsTree.
type GetCategoriesAsTreeParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetCategoryGroupsParams defines parameters for GetCategoryGroups.
type GetCategoryGroupsParams struct {
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Name   *string `form:"name,omitempty" json:"name,omitempty"`
}

// GetCategoryGroupCategoriesByGroupIdParams defines parameters for GetCategoryGroupCategoriesByGroupId.
type GetCategoryGroupCategoriesByGroupIdParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Level  *int `form:"level,omitempty" json:"level,omitempty"`
}

// GetHolidaysParams defines parameters for GetHolidays.
type GetHolidaysParams struct {
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To   *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// GetImportsParams defines parameters for GetImports.
type GetImportsParams struct {
	ResourceType ResourceType `form:"resourceType" json:"resourceType"`
	Offset       *int         `form:"offset,omitempty" json:"offset,omitempty"`
	Limit        *int         `form:"limit,omitempty" json:"limit,omitempty"`
}

// UploadFileParams defines parameters for UploadFile.
type UploadFileParams struct {
	ResourceType ResourceType `form:"resourceType" json:"resourceType"`
}

// GetManagersAndStoresParams defines parameters for GetManagersAndStores.
type GetManagersAndStoresParams struct {
	Offset       *string `form:"offset,omitempty" json:"offset,omitempty"`
	Limit        *string `form:"limit,omitempty" json:"limit,omitempty"`
	StoreId      *string `form:"storeId,omitempty" json:"storeId,omitempty"`
	StoreName    *string `form:"storeName,omitempty" json:"storeName,omitempty"`
	ManagerName  *string `form:"managerName,omitempty" json:"managerName,omitempty"`
	ManagerEmail *string `form:"managerEmail,omitempty" json:"managerEmail,omitempty"`
}

// DeleteManagersJSONBody defines parameters for DeleteManagers.
type DeleteManagersJSONBody struct {
	Managers *[]ManagerObject `json:"managers,omitempty"`
}

// GetManagersParams defines parameters for GetManagers.
type GetManagersParams struct {
	Offset *string `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *string `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateManagersJSONBody defines parameters for CreateManagers.
type CreateManagersJSONBody struct {
	Managers *[]ManagerObject `json:"managers,omitempty"`
}

// GetProductsParams defines parameters for GetProducts.
type GetProductsParams struct {
	Q      *string                 `form:"q,omitempty" json:"q,omitempty"`
	Sort   *GetProductsParamsSort  `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *GetProductsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	Offset *int                    `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int                    `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetProductsParamsSort defines parameters for GetProducts.
type GetProductsParamsSort string

// GetProductsParamsOrder defines parameters for GetProducts.
type GetProductsParamsOrder string

// GetStoresParams defines parameters for GetStores.
type GetStoresParams struct {
	Q      *string               `form:"q,omitempty" json:"q,omitempty"`
	Email  *string               `form:"email,omitempty" json:"email,omitempty"`
	Sort   *GetStoresParamsSort  `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *GetStoresParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	Offset *string               `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *string               `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetStoresParamsSort defines parameters for GetStores.
type GetStoresParamsSort string

// GetStoresParamsOrder defines parameters for GetStores.
type GetStoresParamsOrder string

// GetStoresSalesParams defines parameters for GetStoresSales.
type GetStoresSalesParams struct {
	Id     *string                    `form:"id,omitempty" json:"id,omitempty"`
	Name   *string                    `form:"name,omitempty" json:"name,omitempty"`
	Sort   *GetStoresSalesParamsSort  `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *GetStoresSalesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	Offset *int                       `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int                       `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetStoresSalesParamsSort defines parameters for GetStoresSales.
type GetStoresSalesParamsSort string

// GetStoresSalesParamsOrder defines parameters for GetStoresSales.
type GetStoresSalesParamsOrder string

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = Category

// UpdateCategoryGroupJSONRequestBody defines body for UpdateCategoryGroup for application/json ContentType.
type UpdateCategoryGroupJSONRequestBody = CategoryGroupUpdate

// UploadFileMultipartRequestBody defines body for UploadFile for multipart/form-data ContentType.
type UploadFileMultipartRequestBody = FileUpload

// DeleteManagersJSONRequestBody defines body for DeleteManagers for application/json ContentType.
type DeleteManagersJSONRequestBody DeleteManagersJSONBody

// CreateManagersJSONRequestBody defines body for CreateManagers for application/json ContentType.
type CreateManagersJSONRequestBody CreateManagersJSONBody
